import { ArrowLeft, ArrowUpRight, LockKeyhole } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Line = { id: string; family: "neocaridina" | "caridina"; name: string; description: string; availability: "available" | "limited" | "accepting_requests" | "out_of_stock" | "coming_soon"; price: number; quantity: number; minimum_order: number; image_url: string | null; shipping_placeholder: string; live_arrival_placeholder: string; payment_placeholder: string };
const labels: Record<Line["availability"], string> = { available: "In stock", limited: "Limited availability", accepting_requests: "Accepting requests", out_of_stock: "Out of stock", coming_soon: "Coming soon" };
const familyImages = { neocaridina: "/assets/ebi-tsu-neocaridina.png", caridina: "/assets/ebi-tsu-caridina.png" };
export default function LineDetail() { const [, params] = useRoute("/catalog/:id"); const [line, setLine] = useState<Line | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { if (!params?.id) return; supabase.from("inventory_items").select("id, family, name, description, availability, price, quantity, minimum_order, image_url, shipping_placeholder, live_arrival_placeholder, payment_placeholder").eq("id", params.id).maybeSingle().then(({ data }) => { setLine(data as Line | null); setLoading(false); }); }, [params?.id]); if (loading) return <div className="catalog-detail page-width"><p className="catalog-loading">Loading line...</p></div>; if (!line) return <div className="catalog-detail page-width"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to home</Link><h1>Line not found.</h1><Link href="/neocaridina" className="text-link">Return to collections <ArrowUpRight size={15} /></Link></div>; const image = line.image_url || familyImages[line.family]; return <div className="catalog-detail"><section className="catalog-detail__hero page-width"><Link href={`/${line.family}`} className="back-link"><ArrowLeft size={15} /> Back to {line.family}</Link><div className="catalog-detail__grid"><figure><img src={image} alt={`${line.name} shrimp placeholder`} /><figcaption>{line.family} / visual placeholder</figcaption></figure><div><span className="section-label"><span>—</span> {line.family} line</span><h1>{line.name}</h1><p>{line.description}</p><span className={`catalog-detail__status catalog-detail__status--${line.availability}`}><span /> {labels[line.availability]}</span><div className="catalog-detail__facts"><span><small>Price</small>{line.price === 0 ? "$0 placeholder" : `$${line.price.toFixed(2)}`}</span><span><small>Quantity</small>{line.quantity}</span><span><small>Minimum order</small>{line.minimum_order}</span></div>{line.availability === "out_of_stock" && <p className="catalog-detail__notice"><LockKeyhole size={15} /> This line is currently unavailable. You may still submit a request for future availability.</p>}<Link href={`/livestock-request?line=${line.id}`} className="button button--dark">Request {line.name} <ArrowUpRight size={15} /></Link></div></div></section><section className="catalog-detail__policies section-pad"><div className="page-width"><span className="section-label"><span>—</span> Before availability</span><div className="catalog-detail__policy-grid"><div><h2>Shipping</h2><p>{line.shipping_placeholder}</p></div><div><h2>Live arrival</h2><p>{line.live_arrival_placeholder}</p></div><div><h2>Payment</h2><p>{line.payment_placeholder}</p></div></div></div></section></div>; }
