import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Mail, Send } from "lucide-react";
import { Link, useLocation } from "wouter";
import type { User } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

export default function LivestockRequest() {
  const [user, setUser] = useState<User | null>(null);
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [location] = useLocation();
  const [selectedLine, setSelectedLine] = useState<{ id: string; name: string; family: string } | null>(null);
  useEffect(() => { const id = new URLSearchParams(window.location.search).get("line"); if (id) supabase.from("inventory_items").select("id, name, family").eq("id", id).maybeSingle().then(({ data }) => setSelectedLine(data)); let mounted = true; supabase.auth.getUser().then(({ data }) => { if (mounted) setUser(data.user); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { if (mounted) setUser(session?.user ?? null); }); return () => { mounted = false; listener.subscription.unsubscribe(); }; }, []);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!user) return; setBusy(true); setSubmitted(false); setError("");
    const form = new FormData(event.currentTarget);
    const name = String(form.get("name") || "").trim(); const phone = String(form.get("phone") || "").trim(); const species = String(form.get("species") || ""); const quantityValue = String(form.get("quantity") || "").trim(); const quantity = quantityValue ? Number(quantityValue) : null; const shippingLocation = String(form.get("shipping_location") || "").trim(); const preferredLine = String(form.get("preferred_line") || "").trim(); const timeframe = String(form.get("timeframe") || "").trim(); const notes = String(form.get("notes") || "").trim();
    const requestNotes = [`Preferred line: ${selectedLine?.name || preferredLine || "Not specified"}`, `Preferred timeframe: ${timeframe || "Not specified"}`, "", notes].join("\n");
    const { error: insertError } = await supabase.from("livestock_requests").insert({ user_id: user.id, name, email, phone: phone || null, species, quantity, shipping_location: shippingLocation || null, inventory_item_id: selectedLine?.id || null, selected_line: selectedLine?.name || preferredLine || null, notes: requestNotes });
    if (insertError) { setError("We couldn’t save your livestock request. Please try again."); setBusy(false); return; }
    event.currentTarget.reset(); setEmail(""); setSubmitted(true); setBusy(false);
    const { error: emailError } = await supabase.functions.invoke("send-inquiry-email", { body: { name, email, phone, inquiryType: "Livestock request", message: [`Species: ${species}`, `Quantity: ${quantity ?? "Not specified"}`, `Shipping location: ${shippingLocation || "Not specified"}`, `Selected line: ${selectedLine?.name || preferredLine || "Not specified"}`, requestNotes].join("\n") } });
    if (emailError) setError("Your request was saved to your account, but email delivery could not be completed yet. Please try again shortly.");
  }

  return <div className="contact-page livestock-page"><section className="contact-hero page-width"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to home</Link><div className="section-label"><span>07</span> Livestock request</div><div className="contact-hero__grid"><div><h1>Find your<br /><em>colony.</em></h1><p>{selectedLine ? <>You are requesting <strong>{selectedLine.name}</strong>. </> : null}Tell us what you’re looking for. Requests help us understand your needs and match future availability thoughtfully—no payment is taken here.</p><a className="contact-email" href="mailto:Ebi-Tsu@outlook.com"><Mail size={16} /> Ebi-Tsu@outlook.com <ArrowUpRight size={15} /></a></div><div className="contact-form-wrap">{!user && <div className="form-notice" role="status">Please <Link href="/account">create an account or log in</Link> before submitting a livestock request.</div>}{submitted && <div className="form-notice form-notice--success" role="status"><strong>Request received.</strong><br />We saved your request to your account and sent it to Ebi Tsū for review.</div>}{error && <div className="form-error" role="alert">{error}</div>}<form className="contact-form" onSubmit={handleSubmit}><div className="form-row"><label>Name *<input required name="name" autoComplete="name" disabled={!user} /></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" disabled={!user} /></label></div><label>Email address *<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} disabled={!user} /></label><div className="form-row"><label>Species *<select required name="species" defaultValue="" disabled={!user}><option value="" disabled>Select species</option><option value="neocaridina">Neocaridina</option><option value="caridina">Caridina</option><option value="either">Either</option><option value="not_sure">Not sure yet</option></select></label><label>Quantity<input name="quantity" type="number" min="1" inputMode="numeric" disabled={!user} /></label></div><label>Preferred breeding line<input name="preferred_line" value={selectedLine?.name || undefined} onChange={() => undefined} placeholder="Optional — if you have one in mind" disabled={!user} /></label><label>Shipping location *<input required name="shipping_location" placeholder="City, state, or country" autoComplete="country-name" disabled={!user} /></label><label>Preferred timeframe<input name="timeframe" placeholder="Optional" disabled={!user} /></label><label>Additional notes<textarea name="notes" rows={5} placeholder="Tell us what you’re looking for." disabled={!user} /></label><button className="form-submit" disabled={!user || busy} type="submit">{busy ? "Sending..." : "Send livestock request"} <Send size={16} /></button></form><p className="form-note">This is a request, not a purchase. We’ll review availability and follow up directly.</p></div></div></section></div>;
}
